### PR TITLE
Ft allow loaded keyspec

### PR DESCRIPTION
**Pull request by fredrikt**

### CODE REVIEW

**Comment by leifj** [comment]
Är detta aktuellt fortfarande - kan du uppdatera din PR isåfall?

**Comment by leifj** [comment]
is this relevant given PR#44?

**Comment by fredrikt** [comment]
Do you think it is possible to avoid re-creating keyspecs with #44 applied? I couldn't really tell from looking at the diff of #44.

**Comment by sklemer1** [comment]
Why and when would you want to pre-load the key specs? #44 doesn't change anything about this; neither in favor nor against it :).

**Comment by fredrikt** [comment]
Two and a half years is a long time - I must admit I don't recall what I was working on when I made this pull request. I'm pretty sure it was something where initialisation was really time consuming - probably with a remote HSM.

**Comment by leifj** [comment]
HSM init is slow yes

**Pull request closed without merging**
